services:
  redis:
    image: redis:latest
    container_name: drl-redis-test
    hostname: drl-redis-test
    networks:
      - drl-network-test
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10

  test:
    container_name: drl-api-server-test
    hostname: drl-api-server-test
    build:
      context: .
      target: test
    networks:
      - drl-network-test
    environment:
      DRL_REDIS_HOSTNAME: drl-redis-test
      DRL_REDIS_PORT: 6379
      DRL_REDIS_PASSWORD: ""
    depends_on:
      redis:
        condition: service_healthy

networks:
  drl-network-test:
