services:
  redis:
    image: redis:latest
    container_name: drl-redis
    hostname: drl-redis
    networks:
      - drl-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10

  app:
    container_name: drl-api-server
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - drl-network
    depends_on:
      redis:
        condition: service_healthy

networks:
  drl-network:
